server:
  port: 8090

thread-pool:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 5

shadow:
  mqtt:
    host: 120.78.133.4
    port: 1883
    username: guest
    password: guest
    timeout: 60
    keepAlive: 180
    preFix: 'tcp://'
    clientId: shadowTest
